#!/bin/sh

### BEGIN INIT INFO
# Provides:       zoe
# Required-Start: $network
# Required-Stop:  $network
# Default-Start:  2 3 5
# Default-Stop:   0 1 6
# Description:    ZOE Operating Engine
### END INIT INFO

case "$1" in
	start)
		/home/zoe/platform/bin/srv/zoe --boot=all
		;;
	stop)
		/home/zoe/platform/bin/srv/zoe --shut=all
		;;
	restart)
		/home/zoe/platform/bin/srv/zoe --shut=all
		/home/zoe/platform/bin/srv/zoe --boot=all
		;;
	status)
		/home/zoe/platform/bin/srv/zoe --list=all
		;;
esac
