.TH zoe 1 "ZOE Operating Engine" "2015-09-06" "ZOE Operating Engine"
.SH DESCRIPTION
.PP
平台唯一的服务,负责处理所有业务的渠道请求.
.PP
.SH OPTION
.TP
\fB\-b\fR,\fB\-\-boot\fR \fIBsnCode\fR
启动BsnCode指定的业务,all代表启动业务目录下的全部业务.
.TP
\fB\-s\fR,\fB\-\-shut\fR \fIBsnCode\fR
停止BsnCode指定的业务,all代表停止业务目录下的全部业务.
.TP
\fB\-b\fR,\fB\-\-boot\fR \fIBsnCode\fR
显示BsnCode指定的业务,all代表显示业务目录下的全部业务.
.SH AUTHOR
陈乐群
.SH COPYRIGHT
昆明软景科技开发有限公司
.SH SEE ALSO
.BR dbs(1)
.BR emu(1)
